version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "skaSam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4dg4k2trji2w"
s3_prefix = "skaSam-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
